### ISSUE TITLE
get data problem

### ISSUE THREAD

**Issue by li-car-fei** [serkansulun/midi-emotion#2]
when I run the `run.py` to get data, it stop but not do not throw out errors, how can I get the data ?

**Comment by serkansulun** [comment]
Can you try debugging and see at which line it gets stuck?

**Comment by serkansulun** [comment]
Please see https://github.com/serkansulun/midi-emotion/issues/3#issuecomment-1339164091

**Comment by xlblthh** [comment]
Why can't I get data when running run.py
